Feat/string mocker improvement
NeuraLegion/openapi-sampler pull request #5
Opened 2019-10-31 15:53 UTC by sixaphone

2019-10-31 16:47 UTC, derevnjuk requested changes

2019-10-31 16:47 UTC, ArtemDerevnjuk commented on src/samplers/string.js
> +  return Buffer.from('Hello Mock').toString('base64');
```suggestion
  return Buffer.from(faker.lorem.word()).toString('base64');
```

2019-10-31 16:47 UTC, ArtemDerevnjuk commented on src/samplers/string.js
>    return 'http://example.com';
```suggestion
   return faker.internet.url();
```

2019-10-31 16:47 UTC, derevnjuk commented on src/samplers/string.js
>    return 'http://example.com';
Please, use random data

2019-10-31 16:57 UTC, derevnjuk commented
@sixaphone Maybe we try to add support `not`. What do you think?

2019-10-31 17:23 UTC, sixaphone commented
Sure i think i can do that no prob

2019-11-01 13:39 UTC, derevnjuk requested changes

2019-11-01 13:39 UTC, ArtemDerevnjuk commented on src/samplers/string.js
> +    let format = schema.pattern !== undefined ? 'pattern' : schema.format || 'default';
What  happens, if `pattern` will be `null`?

2019-11-01 16:51 UTC, derevnjuk requested changes

2019-11-01 16:51 UTC, ArtemDerevnjuk commented on src/samplers/string.js
> +    let format = !isBlank(schema.pattern) ? 'pattern' : schema.format || 'default';
You don't need to use `isBlank` here. Just use `schema.pattern` as conditions. It's more suited for this case

```javascript
const format = schema.pattern ? 'pattern' : (schema.format || 'default');
```

2019-11-02 19:16 UTC, derevnjuk approved these changes

2019-11-02 19:18 UTC, merged