Add allOf array && improve array/number mocker
NeuraLegion/openapi-sampler pull request #9
Opened 2019-11-05 14:54 UTC by sixaphone

2019-11-05 15:50 UTC, derevnjuk requested changes

2019-11-05 15:50 UTC, derevnjuk commented on src/allOf.js
> +    if (res.type === 'array' ) {
Use `switch` or merge `if/else` declarations

2019-11-05 15:50 UTC, derevnjuk commented on src/utils.js
> +  }
Really? Well, obviously, you can write it easier.

2019-11-05 15:50 UTC, derevnjuk commented on src/utils.js
> +export function nestedTypeLookup(schema) {
What is it doing at all? OAS clearly defines available keywords.

2019-11-05 15:50 UTC, derevnjuk commented on src/allOf.js
> +
You should check and throw an exception on schemas with different types here

2019-11-05 15:50 UTC, derevnjuk commented on src/allOf.js
> +      if (!arraySchema.items) {
`items` is required in `array`. See https://swagger.io/docs/specification/data-models/data-types/#array

2019-11-05 15:50 UTC, derevnjuk commented on src/samplers/array.js
> +
We don't need to support `uniqueItems`. It's unhelpful in mock context

2019-11-05 15:50 UTC, derevnjuk commented on test/integration.spec.js
> +    it('allOf array of at least two numbers', function() {
Bring test titles into line with others.

2019-11-06 08:19 UTC, sixaphone commented on src/allOf.js
> +
is that not handled by the loop above, the `subSamples`.
Or do you mean array types

2019-11-06 09:34 UTC, ArtemDerevnjuk commented on src/allOf.js
> +
We've already discussed it with us. The types can't be merged, if they are logical incompatible. It mean `string` can't be combined with `integer` and etc.

2019-11-06 13:28 UTC, ArtemDerevnjuk commented on src/allOf.js
> +
@sixaphone Seems it's my fault. We've already handled that case.
https://github.com/NeuraLegion/openapi-sampler/blob/ec9fae76ddd78e4931d347993cd4ccacbad0d114/src/allOf.js#L14
Following schema is allowed also. It mean `array` can contain both string and number items.

```json
{
   "allOf": [
      {
         "type": "array",
         "items": {
            "type": "number"
         }
      },
      {
         "items": {
            "type": "string"
         },
         "minItems": 2,
         "maxItems": 3
      }
   ]
}
```

2019-11-06 13:44 UTC, sixaphone commented on src/allOf.js
> +
:sweat_smile:  its okay i still love you, no homo

2019-11-06 14:51 UTC, derevnjuk approved these changes

2019-11-06 14:52 UTC, merged